homeassistant:
  name: Trotacaminos 2
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/Madrid
  customize: !include customize.yaml
  customize_glob:
    "*_name":
      icon: mdi:cursor-text
    "*_mac":
      icon: mdi:tag-text-outline
    "*_ip":
      icon: mdi:pound-box
    "*_hardware":
      icon: mdi:wrench
    "*_firmware":
      icon: mdi:code-brackets
    "*_firmware_version":
      icon: mdi:code-tags
    "*2home":
      friendly_name: Tiempo Est. a Casa
      icon: mdi:timelapse
    "*2work":
      friendly_name: Tiempo Est. al Trabajo
      icon: mdi:timelapse
    "*iluminancia_*":
      icon: mdi:brightness-5
    "*temperatura_*":
      icon: mdi:thermometer
    "*humedad_*":
      icon: mdi:water-percent

frontend:

logger:
  default: debug

map:

config:

http:
  base_url: !secret ha_url
  api_password: !secret ha_password
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: True
  login_attempts_threshold: 10

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: !secret addon_configurator_url

updater:
  include_used_components: true

discovery:

conversation:

history:

logbook:

sun:

tts:
  platform: google

mqtt:
  broker: core-mosquitto
  port: !secret mqtt_port
  client_id: !secret mqtt_client_id
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true
  discovery_prefix: homeassistant
  keepalive: 120

light:
 - platform: yeelight
   devices:
     192.168.1.131:
       name: Lampara Pie
     192.168.1.132:
       name: Luz Ambiente

device_tracker:
  - platform: gpslogger
  - platform: nmap_tracker
    hosts: 192.168.1.1-255
    track_new_devices: False
    consider_home: 900
    interval_seconds: 10
    home_interval: 5
    scan_options: " --privileged -sP "

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_chat_id
      
twilio:
  account_sid: !secret twilio_account_ssid
  auth_token: !secret twilio_auth_token

notify:
  - name: telegram_daniel
    platform: telegram
    chat_id: !secret telegram_chat_id
  - name: sms
    platform: twilio_sms
    from_number: !secret twilio_from_number
  - name: html5
    platform: html5
    gcm_api_key: !secret html5_api_key
    gcm_sender_id: !secret html5_sender_id
  - name: html5_daniel
    platform: group
    services:
      - service: html5
        data:
          target: "daniel"
  - name: html5_ramon
    platform: group
    services:
      - service: html5
        data:
          target: "ramon"
  - name: html5_mcarmen
    platform: group
    services:
      - service: html5
        data:
          target: "mcarmen"
  - name: html5_family
    platform: group
    services:
      - service: html5_daniel
      - service: html5_ramon
      - service: html5_mcarmen

media_player:
  - platform: gpmdp
    host: 192.168.1.150

google_assistant:
  project_id: !secret google_assistant_project_id
  client_id: !secret google_assistant_client_id
  access_token: !secret google_assistant_access_token
  exposed_domains:
    - switch
    - light

vacuum:
  - platform: xiaomi_miio
    name: Aspi
    host: !secret aspi_host
    token: !secret aspi_token

### DIRECTORIES ###
automation: !include automations.yaml
group: !include groups.yaml
input_boolean: !include inputs/input_boolean.yaml
input_select: !include inputs/input_select.yaml
scene: !include scenes.yaml
script: !include_dir_merge_named scripts/
sensor: !include_dir_list sensors/
binary_sensor: !include_dir_list binary_sensors/
zone: !include_dir_list zones/