homeassistant:
  name: Trotacaminos 2
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/Madrid

  customize:
    sensor.aquaris_x5_plus:
      icon: mdi:battery-60
    sensor.motorola:
      icon: mdi:battery-60
    script.car_finder_notify:
      friendly_name: Enviar ubicación del coche
      icon: mdi:car-connected
    script.refresh_devices:
      friendly_name: Actualizar Loc/Bat
      icon: mdi:account-location
    sensor.daniel2home:
      friendly_name: ETA Casa
      icon: mdi:av-timer
    sensor.ramon2home:
      friendly_name: ETA Casa
      icon: mdi:av-timer
    sensor.rpi3_temperature:
      friendly_name: RPi3 Temperatura
      icon: mdi:thermometer

frontend:

http:
  base_url: !secret ha_url
  api_password: !secret ha_password
  ip_ban_enabled: True
  login_attempts_threshold: 3

updater:

discovery:

conversation:

tts:
  - platform: google
    language: 'es'

history:

logbook:

sun:

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  client_id: !secret mqtt_client_id
  username: !secret mqtt_username
  password: !secret mqtt_password
  
light:
  - platform: mqtt
    name: Luz Principal
    state_topic: "/home/daniel-bedroom/lights/main"
    command_topic: "/home/daniel-bedroom/lights/main/set"
    qos: 1
    retain: true
  - platform: mqtt
    name: Luz Pasillo
    state_topic: "/home/daniel-bedroom/lights/corridor"
    command_topic: "/home/daniel-bedroom/lights/corridor/set"
    qos: 1
    retain: true
  - platform: mqtt
    name: Luz Cama
    state_topic: "/home/daniel-bedroom/lights/bed"
    command_topic: "/home/daniel-bedroom/lights/bed/set"
    qos: 1
    retain: true
  - platform: mqtt
    name: Lamparita
    state_topic: "/home/entrance/lights/lamp"
    command_topic: "/home/entrance/lights/lamp/set"
    qos: 1
    retain: true
  - platform: mqtt
    name: Lampara Mesa 
    state_topic: "/home/livingroom/lights/lamp"
    command_topic: "/home/livingroom/lights/lamp/set"
    qos: 1
    retain: true
  - platform: yeelight
    devices:
      192.168.1.131:
        name: Lampara Pie
      192.168.1.132:
        name: Luz Ambiente

switch:
  - platform: mqtt
    name: "Enchufe"
    state_topic: "/home/daniel-bedroom/socket"
    command_topic: "/home/daniel-bedroom/socket/set"
    qos: 1
    retain: true
  - platform: mqtt
    name: "Radiador"
    state_topic: "/home/daniel-bedroom/radiator"
    command_topic: "/home/daniel-bedroom/radiator/set"
    qos: 1
    retain: true

cover:
  - platform: mqtt
    name: "Persiana"
    state_topic: "/home/daniel-bedroom/blind"
    command_topic: "/home/daniel-bedroom/blind/set"
    state_open: "OPEN"
    state_closed: "CLOSE"

device_tracker:
  - platform: owntracks
    max_gps_accuracy: 200
    waypoints: True
  - platform: nmap_tracker
    hosts: 192.168.1.1/24
    consider_home: 0:8:00
    interval_seconds: 1

notify:
  - name: notify
    platform: telegram
    api_key: !secret telegram_api_key
    chat_id: !secret telegram_chat_id

media_player:
  - platform: lg_netcast
    name: Televisión LG
    host: !secret lg_netcast_host
    access_token: !secret lg_netcast_access_token
  - platform: kodi
    host: http://192.168.1.109


#### DIRECTORIES ####

zone: !include_dir_list zones/
weather: !include_dir_list weather/
sensor: !include_dir_list sensors/
input_select: !include inputs/input_select.yaml
input_boolean: !include inputs/input_boolean.yaml
group: !include groups.yaml
automation: !include_dir_list automations/
script: !include_dir_merge_named scripts/
