alias: "Away"
trigger:
  - platform: zone
    event: leave
    zone: zone.home
    entity_id: device_tracker.daniel_aquarisx5plus
condition:
  - condition: and
    conditions:
      - condition: state
        entity_id: group.bedroomligths
        state: "on"
action:
  - service: script.all_lights_off
  - service: notify.notify
    data:
      message: "¡Te dejaste las luces encendidas! Las he apagado por ti"