alias: "Away"
trigger:
  - platform: state
    entity_id: group.daniel
    from: 'home'
    to: 'not_home'
condition:
  - condition: and
    conditions:
      - condition: state
        entity_id: group.bedroom_ligths
        state: "on"
action:
  - service: script.all_lights_off
  - service: notify.notify
    data:
      message: "¡Te dejaste las luces encendidas! Las he apagado por ti"