alias: "Daniel Bedtime"
trigger:
  platform: state
  entity_id: input_boolean.daniel_bedtime
  state: "on"
condition:
  - condition: and
    conditions:
      - condition: state
        entity_id: sensor.daniel_home
        state: 'home'
      - condition: template
        value_template: '{{ states.input_select.daniel_status.state != "durmiendo" }}'
action:
  - service: script.daniel_bedtime