alias: "Daniel not Driving"
trigger:
  platform: state
  entity_id: input_select.daniel_status
  from: "conduciendo"
  to: "standby"
action:
  - service: notify.notify
    data:
      message: "Daniel is not in the car!"
  - service: script.refresh_devices
  - delay:
      seconds: 10
  - service: script.driving_daniel_stop