alias: "Daniel Bedtime"
trigger:
  platform: state
  entity_id: input_boolean.daniel_bedtime
  state: "on"
condition:
  - condition: and
    conditions:
      - condition: state
        entity_id: group.daniel
        state: "home"
action:
  - service: script.daniel_bedtime