alias: "Daniel Bedtime Welcome"
trigger:
  - platform: state
    entity_id: group.daniel
    from: 'not_home'
    to: 'home'
condition:
  - condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.daniel_bedtime
        state: "on"
action:
  - service: script.daniel_bedtime