alias: Login Failure
trigger:
  platform: template
  value_template: >
    {% if states("persistent_notification.httplogin") != "unknown" %}
      true
    {% else %}
      false
    {% endif %}
action:
- service: notify.telegram_daniel
  data:
    title: Alerta por intrusión
    message: Ha habido un intento de login fallido. Accede a Home Assistant para más detalles