alias: Mark person as away from sleeping
trigger:
- platform: state
  entity_id: input_select.daniel_home_status
  to: Durmiendo
  for:
    hours: 11
- platform: state
  entity_id: input_select.ramon_home_status
  to: Durmiendo
  for:
    hours: 11
- platform: state
  entity_id: input_select.mcarmen_home_status
  to: Durmiendo
  for:
    hours: 11
- platform: state
  entity_id: input_select.amanda_home_status
  to: Durmiendo
  for:
    hours: 11
condition:
  condition: or
  conditions:
  - condition: template
    value_template: >
      {% if trigger.entity_id == "input_select.daniel_home_status" and states.device_tracker.daniel.state != "home" and states.input_select.daniel_home_status.state == "Durmiendo" %}
        true
      {% else %}
        false
      {% endif %}
  - condition: template
    value_template: >
      {% if trigger.entity_id == "input_select.ramon_home_status" and states.device_tracker.ramon.state != "home" and states.input_select.ramon_home_status.state == "Durmiendo" %}
        true
      {% else %}
        false
      {% endif %}
  - condition: template
    value_template: >
      {% if trigger.entity_id == "input_select.mcarmen_home_status" and states.device_tracker.mcarmen.state != "home" and states.input_select.mcarmen_home_status.state == "Durmiendo" %}
        true
      {% else %}
        false
      {% endif %}
  - condition: template
    value_template: >
      {% if trigger.entity_id == "input_select.amanda_home_status" and states.device_tracker.amanda.state != "home" and states.input_select.amanda_home_status.state == "Durmiendo" %}
        true
      {% else %}
        false
      {% endif %}
action:
- service: input_select.select_option
  data_template:
    entity_id: >
     {% if trigger.entity_id == "input_select.daniel_home_status" %}
        input_select.daniel_home_status
      {% elif trigger.entity_id == "input_select.ramon_home_status" %}
        input_select.ramon_home_status
      {% elif trigger.entity_id == "input_select.mcarmen_home_status" %}
        input_select.mcarmen_home_status
      {% elif trigger.entity_id == "input_select.amanda_home_status" %}
        input_select.amanda_home_status
      {% endif %}