alias: "Motion Daniel Bedroom ON"
trigger:
  - platform: state
    entity_id: binary_sensor.pir_habitacion_daniel
    from: "off"
    to: "on"
  - platform: sun
    event: sunset
    offset: '-00:15:00'
condition:
  - condition: and
    conditions:
      - condition: time
        after: '18:00:00'
        before: '01:00:00'
      - condition: sun
        after: sunset
        after_offset: "-00:15:00"
      - condition: state
        entity_id: binary_sensor.pir_habitacion_daniel
        state: "on"
action:
  - service: light.turn_on
    entity_id: light.luz_principal