alias: New device connected
trigger:
- platform: event
  event_type: device_tracker_new_device
action:
- service: persistent_notification.create
  data:
    title: Nueva dispositivo conectado
    message: Nuevo dispositivo {{trigger.event.data.host_name}} ({{trigger.event.data.entity_id}}) detectado
    notification_id: new_device_connected
- service: notify.html5_daniel
  data_template:
    title: Nuevo dispositivo conectado
    message: Nuevo dispositivo {{trigger.event.data.host_name}} ({{trigger.event.data.entity_id}}) detectado