alias: "Radiators Auto OFF"
trigger:
  - platform: time
    after: '16:00:00'
condition:
  - condition: and
    conditions:
      - condition: template
        value_template: '{{ states.sensor.medium_temp_calculation.state | float > states.input_select.radiators_threshold_temperature.state | float }}'
action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.radiators_tomorrow