alias: "Apagado Automatico Radiador Daniel"
trigger:
  - platform: time
    minutes: '/30'
    seconds: 0
condition:
  - condition: and
    conditions:
      - condition: template
        value_template: '{{ now().time().strftime("%H:%M") == states.input_select.radiator_daniel_time_off.state }}'
action:
  - service: switch.turn_off
    entity_id: switch.radiator_daniel