alias: Encendido Automatico Radiador Daniel
trigger:
- platform: time_pattern
  minutes: /30
condition:
- condition: and
  conditions:
  - condition: state
    entity_id: input_boolean.radiators_tomorrow
    state: "on"
action:
- service: switch.turn_on
  entity_id: switch.radiador_daniel
- delay: 00:02
- service: switch.turn_on
  entity_id: switch.radiador_daniel
- delay: 00:02
- condition: and
  conditions:
  - condition: state
    entity_id: switch.radiador_daniel
    state: "off"
- service: notify.telegram_daniel
  data_template:
    message: El Radiador Daniel no ha podido encenderse a la hora especificada. Comprobar el estado del dispositivo ya que algunas funcionalidades dejarán de estar disponibles