alias: "Daniel Welcome"
trigger:
  - platform: state
    entity_id: group.ramon
    from: 'not_home'
    to: 'home'
condition:
  condition: and
  conditions:
    - condition: time
      after: '12:00:00'
      before: '02:30:00'
action:
  - service: script.welcome_home_ramon
  - service: script.welcome_home