alias: Marcar Casa como Vacaciones desde Deshabitada
trigger:
- platform: state
  entity_id: input_select.daniel_home_status
  to: Ausente
- platform: state
  entity_id: input_select.ramon_home_status
  to: Ausente
- platform: state
  entity_id: input_select.mcarmen_home_status
  to: Ausente
- platform: state
  entity_id: input_select.amanda_home_status
  to: Ausente
- platform: state
  entity_id: input_select.andrea_home_status
  to: Ausente
- platform: state
  entity_id: input_select.arturo_home_status
  to: Ausente
condition:
- condition: and
  conditions:
  - condition: state
    entity_id: input_select.home_status
    state: Deshabitada
  - condition: state
    entity_id: input_select.daniel_home_status
    state: Ausente
  - condition: state
    entity_id: input_select.ramon_home_status
    state: Ausente
  - condition: state
    entity_id: input_select.mcarmen_home_status
    state: Ausente
  - condition: state
    entity_id: input_select.amanda_home_status
    state: Ausente
  - condition: state
    entity_id: input_select.andrea_home_status
    state: Ausente
  - condition: state
    entity_id: input_select.arturo_home_status
    state: Ausente
action:
- service: input_select.select_option
  data:
    entity_id: input_select.home_status
    option: Vacaciones