alias: Encendido Automatico Termo
trigger:
- platform: time_pattern
  minutes: /30
condition:
- condition: or
  conditions:
  - condition: template
    value_template: >
      {% if now().time().strftime("%H:%M") == states.input_select.termo_time_on1.state %}
        true
      {% else %}
        false
      {% endif %}
  - condition: template
    value_template: >
      {% if now().time().strftime("%H:%M") == states.input_select.termo_time_on2.state %}
        true
      {% else %}
        false
      {% endif %}
  - condition: template
    value_template: >
      {% if now().time().strftime("%H:%M") == states.input_select.termo_time_on3.state %}
        true
      {% else %}
        false
      {% endif %}
action:
- service: switch.turn_on
  entity_id: switch.termo
- delay: 00:05
- service: switch.turn_on
  entity_id: switch.termo
- delay: 00:05
- condition: and
  conditions:
  - condition: state
    entity_id: switch.termo
    state: "off"
- service: notify.telegram_daniel
  data_template:
    title: Alerta de dispositivo
    message: El Termo no ha podido encenderse a la hora especificada. Comprobar el estado del dispositivo ya que algunas funcionalidades dejarán de estar disponibles