alias: "Apagado Automatico Termo"
trigger:
  - platform: time
    minutes: '/30'
    seconds: 0
condition:
  - condition: or
    conditions:
      - condition: template
        value_template: '{{ now().time().strftime("%H:%M") == states.input_select.termo_time_off1.state }}'
      - condition: template
        value_template: '{{ now().time().strftime("%H:%M") == states.input_select.termo_time_off2.state }}'
      - condition: template
        value_template: '{{ now().time().strftime("%H:%M") == states.input_select.termo_time_off3.state }}'
action:
  - service: switch.turn_off
    entity_id: switch.enchufe