alias: Vaciado Aspi
trigger:
- platform: state
  entity_id: input_boolean.dash_dolce1
condition:
- condition: and
  conditions:
  - condition: state
    entity_id: input_boolean.aspi_llena
    state: "on"
action:
- service: input_boolean.turn_off
  data:
    entity_id: input_boolean.aspi_llena