alias: "Welcome Amanda"
trigger:
  - platform: state
    entity_id: device_tracker.amanda_aquarisa45
    from: 'not_home'
    to: 'home'
condition:
  - condition: and
    conditions:
      - condition: time
        after: '12:00:00'
        before: '05:30:00'
action:
  - service: script.welcome_home_amanda
  - service: script.welcome_home