alias: "Welcome M.Carmen"
trigger:
  - platform: state
    entity_id: device_tracker.mcarmen_aquarise54g
    from: 'not_home'
    to: 'home'
condition:
  - condition: and
    conditions:
      - condition: time
        after: '12:00:00'
        before: '05:30:00'
action:
  - service: script.welcome_home_mcarmen
  - service: script.welcome_home